apiVersion: req.nephio.org/v1alpha1
kind: Dependency
metadata: # kpt-merge: /amf
  name: amf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.cucp-example
    specializer.nephio.org/namespace: oai-ran-cucp
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Dependency|default|amf'
spec:
  packageName: oai-amf
  injectors:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
